#define MAINMENU 0  	/* TREE */
#define MD1 9  	/* OBJECT in TREE #0 */
#define MF1 18  	/* OBJECT in TREE #0 */
#define MF2 19  	/* OBJECT in TREE #0 */
#define MF3 21  	/* OBJECT in TREE #0 */
#define MF4 22  	/* OBJECT in TREE #0 */
#define MF5 23  	/* OBJECT in TREE #0 */
#define MA1 26  	/* OBJECT in TREE #0 */
#define MA2 27  	/* OBJECT in TREE #0 */
#define MA3 28  	/* OBJECT in TREE #0 */
#define MA4 29  	/* OBJECT in TREE #0 */
#define MO1 32  	/* OBJECT in TREE #0 */
#define MO2 33  	/* OBJECT in TREE #0 */
#define MO3 34  	/* OBJECT in TREE #0 */
#define MO4 35  	/* OBJECT in TREE #0 */
#define MO5 36  	/* OBJECT in TREE #0 */
#define ASHICED 1  	/* TREE */
#define FILENAME 4  	/* TREE */
#define FNOK 3  	/* OBJECT in TREE #4 */
#define FNCAN 4  	/* OBJECT in TREE #4 */
#define BASEFILE 2  	/* OBJECT in TREE #4 */
#define COLOR 3  	/* TREE */
#define FILETYPE 2  	/* TREE */
#define CBUT 2  	/* OBJECT in TREE #2 */
#define ABUT 4  	/* OBJECT in TREE #2 */
#define ICBUT 3  	/* OBJECT in TREE #2 */
#define IMBUT 5  	/* OBJECT in TREE #2 */
#define COLBUT 20  	/* OBJECT in TREE #3 */
#define COLOR0 2  	/* OBJECT in TREE #3 */
#define COLOR1 10  	/* OBJECT in TREE #3 */
#define COLOR2 3  	/* OBJECT in TREE #3 */
#define COLOR3 11  	/* OBJECT in TREE #3 */
#define COLOR4 4  	/* OBJECT in TREE #3 */
#define COLOR5 12  	/* OBJECT in TREE #3 */
#define COLOR6 5  	/* OBJECT in TREE #3 */
#define COLOR7 13  	/* OBJECT in TREE #3 */
#define COLOR8 6  	/* OBJECT in TREE #3 */
#define COLOR9 14  	/* OBJECT in TREE #3 */
#define COLORA 7  	/* OBJECT in TREE #3 */
#define COLORB 15  	/* OBJECT in TREE #3 */
#define COLORC 8  	/* OBJECT in TREE #3 */
#define COLORD 16  	/* OBJECT in TREE #3 */
#define COLORE 9  	/* OBJECT in TREE #3 */
#define COLORF 17  	/* OBJECT in TREE #3 */
#define CURRCOL 19  	/* OBJECT in TREE #3 */
#define ABBUT 7  	/* OBJECT in TREE #1 */
#define FTOK 10  	/* OBJECT in TREE #2 */
#define FTCAN 11  	/* OBJECT in TREE #2 */
